### ISSUE TITLE
[Visual Design] Create profile/readme.md to represent the Meshery project collective

### ISSUE THREAD

**Issue by leecalcote** [meshery/.github#23]
### Current Behavior
No `meshery` org level profile readme exists.

### Desired Behavior
A pretty, engaging org-level profile that represents the collective capabilities of the project and community.

### Implementation
1. Visual design in Figma.
1. Implementation with graphics and markdown, noting limits imposed by GitHub markdown.

### Mockups
_needed_

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🖥 [Contributing to Meshery UI](https://docs.meshery.io/project/contributing/contributing-ui)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by ShatilKhan** [comment]
@leecalcote I have added the `README` file
Still a lot of work to do. I'll try to finish up by tonight
