### ISSUE TITLE
[Docs] Installation on raspberrypi

### ISSUE THREAD

**Issue by jamieplu** [meshery/.github#30]
### Current State

I'm not sure if this is supported. Is it?

### Desired State

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by hamza-mohd** [comment]
I don't think so. Not unless ARM support has been confirmed.

**Comment by ritzorama** [comment]
> I don't think so. Not unless ARM support has been confirmed.

there is an open issue on ARM support
